
###
GET http://192.168.0.43:3000/accelerometer HTTP/1.1

###
GET http://localhost:3000/accelerometer/5fa45c8f0abd0a30caa181af HTTP/1.1

###

POST http://localhost:3000/accelerometer HTTP/1.1
content-type: application/json

{
    "x":3766,
    "y":15,
    "z":6,
    "pitch":10,
    "roll":-1,
    "inclination":"1",
    "orientation":"1",
    "acceleration":"1",
    "deviceId":"5fa45c8f0abd0a30caa181af"
}

###
GET http://localhost:3000/gyro HTTP/1.1

###
POST http://localhost:3000/gyro HTTP/1.1
Content-type: application/json

{
    "x": 126,
    "y": 126,
    "z": 127,
    "pitch": {
        "rate": 0.27,
        "angle": 3.4
    },
    "roll": {
        "rate": -0.23,
        "angle": -4.67
    },
    "yaw": {
        "rate": -0.3,
        "angle": 6.87
    },
    "isCalibrated":true,
    "deviceId":"5fa45c8f0abd0a30caa181af"
}

###
GET http://localhost:3000/thermometer HTTP/1.1

###

POST http://localhost:3000/thermometer HTTP/1.1
content-type: application/json

{
    "C":22,
    "K":231,
    "F":124,
    "deviceId":"5fa45c8f0abd0a30caa181af"
}

###
GET http://localhost:3000/api/cows HTTP/1.1

###
GET http://localhost:3000/api/cows/5fa0697d2849ad2f2ee3e2a8 HTTP/1.1


###
POST http://localhost:3000/cows HTTP/1.1
Content-Type: application/json

{
    "brand":"chavez",
    "ageMonth":"15",
    "number":"10",
    "entryDate":"2020-10-09T04:00:00.000Z",
    "startingWeight":"205.32",
    "race":"nelore",
    "gender":"male",
    "state":"normal"
}
###
DELETE  http://localhost:3000/api/cows HTTP/1.1


###

POST http://localhost:3000/knnclassifiers HTTP/1.1
Content-Type: application/json

{
    "x":3766,
    "y":15,
    "z":6,
    "pitch":10,
    "roll":-1,
    "inclination":1,
    "orientation":1,
    "acceleration":1,
    "action":"accion",
    "label":0
}

###
POST http://localhost:3000/knnclassifiers/accelerometer HTTP/1.1
Content-Type: application/json

{
    "x":4766,
    "y":15,
    "z":6,
    "pitch":10,
    "roll":-1,
    "inclination":1,
    "orientation":1,
    "acceleration":1,
    "action":"accion",
    "label":4,
    "component":"accelerometer"
}

###
POST http://localhost:3000/knnclassifiers/accelerometer HTTP/1.1
Content-Type: application/json

{
    "x":10,
    "y":15,
    "z":6,
    "pitch":10,
    "roll":-1,
    "inclination":1,
    "orientation":1,
    "acceleration":1,
    "action":"accion",
    "label":1,
    "component":"accelerometer"
}

###
POST http://localhost:3000/streaming/upload HTTP/1.1
Content-Type: application/json

{
    "collectionName":"classifiers",
    "fileName":"dataset.json",
    "filePath": "./dataset.json"
}